---
- name: Conditional Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
     ec2:
       key_name: "{{key_name}}"
       instance_type: "{{instance_type}}"
       image: CentOS 7 x64
       count: 1
       vpc_subnet_id: "{{vpc_subnet_id}}"
       assign_public_ip: yes
       region: "{{region}}"
