---
- name: VPC provisioner
  hosts: localhost
  tasks:
    - name: create VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_cidr}}"
        region: "{{region}}"
        tags:
          Class: Ansible
          Task: VPC