---
- name: Node Exporter Installation
  hosts: localhost
  become: true
  become_method: sudo
  user: prometheus
  tasks:
  - name: Add user
    shell: "sudo useradd --no-create-home --shell /bin/false prometheus"
  - name: Create a file
    shell: "sudo mkdir -p /etc/prometheus"
  - name: Create file
    shell: "sudo mkdir -p /var/lib/prometheus"
  - name: Change permission
    shell: "sudo chown prometheus:prometheus /etc/prometheus"
  - name: Change permission
    shell: "sudo chown prometheus:prometheus /var/lib/prometheus"
  - name: Install Node Exporter
    shell: "sudo wget https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz"
  - name: Unzip Node Exporter file
    shell: "sudo tar xvfz node_exporter-0.18.1.linux-amd64.tar.gz "
  - name: Move the unziped files
    shell: " sudo mv node_exporter-0.18.1.linux-amd64 /etc/prometheus/node_exporter "
  - name: Copy the Node Exporter systemd service file
    template:
      src: node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
#     notify: restart node_exporter
  - name: Systemctl daemon-reload
    shell: "sudo sudo systemctl daemon-reload"
  - name: Restart node_exporte
    shell: "sudo  systemctl start node_exporter"
  - name: Enable 
    shell: "sudo systemctl enable node_exporter"
  - name: Status 
    shell: "sudo systemctl enable node_exporter"
    
### it will work with file  node_exporter.service
